export const SHOW_SNACKBAR = "SHOW_SNACKBAR";
export const HIDE_SNACKBAR = "HIDE_SNACKBAR";
export const SAVE_ACCOUNT_DETAILS = "SAVE_ACCOUNT_DETAILS";
export const CLEAR_ACCOUNT_DETAILS = "CLEAR_ACCOUNT_DETAILS";
